### PARA OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/products

### Insertar un nuevo producto
POST http://localhost:8080/api/products
Content-Type: application/json; charset=utf-8

{
  "name": "Piedras x15",
  "sku": "B15",
  "description": "Solo para gatos grandes",
  "retail_price": 15000.00,
  "cost": 10000.00,
  "stock_quantity": 20,
  "category_id": 1,
  "provider_id": 1
}

### BORRAR PRODUCTO por ID
DELETE http://localhost:8080/api/products/4

### ACTUALIZAR UN PRODUCTO
PATCH http://localhost:8080/api/products/8
Content-Type: application/json; charset=utf-8

{
  "cost": 30000,
  "description":"hola pichis"
}
