### PARA OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/products

### OBTENER UN PRODUCTO POR ID
GET http://localhost:8080/api/products/56fe61eb-95af-48de-95fb-19037cd7fd61

### CREAR NUEVO PRODUCTO
POST http://localhost:8080/api/products
Content-Type: application/json; charset=utf-8

{
  "name": "Bolsa",
  "sku": 2343,
  "description": "Solo para perros grandes",
  "retail_price": 15000.00,
  "cost": 10000.00,
  "stock_quantity": 1,
  "category_id": 1,
  "provider_id": 1
}

### BORRAR PRODUCTO por ID
DELETE http://localhost:8080/api/products/6c9fd1fe-7899-4147-bc79-643402f0bec7
### ACTUALIZAR CAMPO DE JSON POR ID
PATCH http://localhost:8080/api/products/56fe61eb-95af-48de-95fb-19037cd7fd61
Content-Type: application/json; charset=utf-8

{
  "cost": 30000,
  "retail_price":45000
}

### OBTENER PRODUCTO POR NOMBRE 
GET http://localhost:8080/api/products/Perros
