### PARA OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/products

### OBTENER UN PRODUCTO POR ID
GET http://localhost:8080/api/products/6
### Insertar un nuevo producto
POST http://localhost:8080/api/products
Content-Type: application/json; charset=utf-8

{
  "name": "EUKANUBA 23KG",
  "sku": "23KG",
  "description": "Solo para perros grandes",
  "retail_price": 15000.00,
  "cost": 10000.00,
  "stock_quantity": 20,
  "category_id": 1,
  "provider_id": 1
}

### BORRAR PRODUCTO por ID
DELETE http://localhost:8080/api/products/7

### ACTUALIZAR UN PRODUCTO POR ID
PATCH http://localhost:8080/api/products/9
Content-Type: application/json; charset=utf-8

{
  "cost": 30000,
  "description":"hola pichis"
}
